name: CI/CD - Docker + Render

on:
  push:
    branches:
      - main   # se ejecuta cuando hagas push a main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar código del repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Login en Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Construir y subir imagen
      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/hola-mundo-docker:latest

      # 4. Desplegar en Render
      - name: Deploy to Render
        run: |
          curl -X POST \
            -H "Accept: application/json" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            https://api.render.com/v1/services/<SERVICE_ID>/deploys
